# Generated by Django 5.2.17 on 2026-08-27 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('code', models.CharField(help_text='Uppercase code like MENTAL-ABILITY', max_length=50, unique=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(db_index=True)),
                ('question_text', models.TextField(help_text='Original question text, preserves Bengali + LaTeX')),
                ('explanation', models.TextField(blank=True, help_text='Original explanation')),
                ('source_answer', models.CharField(blank=True, help_text='Original answer: a,b,c,d,Blank', max_length=10)),
                ('normalized_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_index=True, max_length=1, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('has_explanation', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=True, help_text='False if Blank/missing answer')),
                ('source_hash', models.CharField(db_index=True, help_text='SHA256 of normalized question text for dedup', max_length=64)),
                ('original_source_text', models.TextField(blank=True, help_text='Keeps raw markdown snippet for audit')),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examsession')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.subject')),
            ],
            options={
                'ordering': ['exam_session', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='WrittenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(db_index=True)),
                ('question_text', models.TextField()),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('set_name', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('model_answer', models.TextField(blank=True, help_text='If available')),
                ('explanation', models.TextField(blank=True)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('original_source_text', models.TextField(blank=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_questions', to='exams.examsession')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_questions', to='questions.subject')),
            ],
            options={
                'ordering': ['exam_session', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.TextField(help_text='Option text, Bengali/LaTeX preserved')),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question')),
            ],
            options={
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['question', 'label'], name='questions_c_questio_8aea4d_idx')],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam_session', 'subject'], name='questions_q_exam_se_c9eaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source_hash'], name='questions_q_source__282e09_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['normalized_answer'], name='questions_q_normali_4bfada_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_resolved'], name='questions_q_is_reso_2966b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam_session', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='writtenquestion',
            unique_together={('exam_session', 'question_number')},
        ),
    ]
