# Generated by Django 5.2.17 on 2026-08-27 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('mode', models.CharField(choices=[('PRACTICE', 'Practice'), ('EXAM', 'Exam Simulation'), ('QUICK', 'Quick Quiz'), ('SUBJECT', 'Subject Practice'), ('WEAK', 'Weak Area'), ('INCORRECT', 'Incorrect Review'), ('BOOKMARKED', 'Bookmarked'), ('RANDOM', 'Random Challenge'), ('DAILY', 'Daily Challenge')], db_index=True, default='PRACTICE', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='For exam mode', null=True)),
                ('question_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='exams.examsession')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.subject')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('PRACTICE', 'Practice'), ('EXAM', 'Exam Simulation'), ('QUICK', 'Quick Quiz'), ('SUBJECT', 'Subject Practice'), ('WEAK', 'Weak Area'), ('INCORRECT', 'Incorrect Review'), ('BOOKMARKED', 'Bookmarked'), ('RANDOM', 'Random Challenge'), ('DAILY', 'Daily Challenge')], default='PRACTICE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('TIMED_OUT', 'Timed Out')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('current_question_index', models.IntegerField(default=0)),
                ('time_remaining_seconds', models.IntegerField(blank=True, null=True)),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.examsession')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='quiz.quiz')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_label', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='questions.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.choice')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('correct_streak', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confidence', models.FloatField(default=0)),
                ('easiness', models.FloatField(default=2.5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='quiz_questi_user_id_bb3102_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'status'], name='quiz_quizat_user_id_47c6be_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'exam_session'], name='quiz_quizat_user_id_e7aa04_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-started_at'], name='quiz_quizat_user_id_9cb705_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='quiz_useran_attempt_225444_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'is_correct'], name='quiz_useran_questio_5395f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
