# Generated by Django 5.2.17 on 2026-08-27 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PREVIEW', 'Preview'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('imported', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('duplicates', models.IntegerField(default=0)),
                ('invalid', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionImportDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('existing_question_id', models.IntegerField(blank=True, null=True)),
                ('similarity', models.FloatField(default=1.0)),
                ('raw_data', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('KEEP', 'Keep Both'), ('MERGE', 'Merge'), ('IGNORE', 'Ignore')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_entries', to='imports_app.questionimport')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('exam_route_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('raw_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports_app.questionimport')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImportWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('exam_route_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('raw_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='imports_app.questionimport')),
            ],
        ),
    ]
