# Generated by Django 5.2.17 on 2026-08-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon or emoji', max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Exam Families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('route_id', models.CharField(db_index=True, help_text='Original route-id, case-sensitive', max_length=100, unique=True)),
                ('exam_type', models.CharField(default='General', help_text='General, Special (Health) etc.', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='e.g., Medical, Dental, Education', max_length=120)),
                ('exam_date', models.DateField(blank=True, db_index=True, null=True)),
                ('marks', models.IntegerField(default=100)),
                ('question_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived'), ('DEMO', 'Demo')], db_index=True, default='ACTIVE', max_length=20)),
                ('source_preview_url', models.URLField(blank=True, max_length=500)),
                ('source_exam_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.examfamily')),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
                'indexes': [models.Index(fields=['exam_family', 'status'], name='exams_exams_exam_fa_33e449_idx'), models.Index(fields=['slug'], name='exams_exams_slug_1c0621_idx'), models.Index(fields=['route_id'], name='exams_exams_route_i_fd0401_idx')],
            },
        ),
    ]
