# Generated by Django 5.2.17 on 2026-08-27 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='e.g., first_answer, century', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('xp_reward', models.IntegerField(default=0)),
                ('rule_type', models.CharField(db_index=True, help_text='Rule engine type', max_length=50)),
                ('rule_threshold', models.IntegerField(default=1)),
                ('rule_config', models.JSONField(blank=True, default=dict)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('xp_threshold', models.IntegerField(help_text='Cumulative XP required to reach this level')),
                ('badge_icon', models.CharField(blank=True, help_text='Bootstrap icon or emoji', max_length=50)),
                ('color', models.CharField(default='#0d6efd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all', 'All Time')], db_index=True, max_length=10)),
                ('xp', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'rank'],
                'unique_together': {('period', 'user', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(choices=[('CORRECT_ANSWER', 'Correct Answer'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('DAILY_CHALLENGE', 'Daily Challenge'), ('PERFECT_QUIZ', 'Perfect Quiz'), ('EXAM_COMPLETED', 'Exam Completed'), ('REVIEW_WRONG', 'Review Wrong Answers'), ('STREAK_BONUS', 'Streak Bonus'), ('ACHIEVEMENT', 'Achievement'), ('MANUAL', 'Manual')], db_index=True, max_length=30)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'source'], name='gamificatio_user_id_995660_idx')],
            },
        ),
    ]
